version: '3'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: laravel
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        expose:
            - "9000"
        networks:
            - laravel-net

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - nginx-proxy-net
            - laravel-net
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=laravel-proxy.local.me # need to added into /etc/hosts on localhost
            - VIRTUAL_PORT=80

    mysql-db:
        image: mysql:5.7.22
        container_name: mysql-db
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql-db
        volumes:
            - mysqldata:/var/lib/mysql/
        networks:
            - laravel-net

networks:
    laravel-net:
        driver: bridge
    nginx-proxy-net:
        external: true

volumes:
    mysqldata:
        driver: local
