version: '3'

services:
    express-js:
          build: 
              context: .
              target: dev
              dockerfile: Dockerfile
          container_name: "express-js"
          command: "npm run start:dev"
          volumes:
              - ".:/src"
              - "node_modules:/src/node_modules"
          expose:
              - "3000"
          restart: "always"
          environment:
            - NODE_ENV=development
            - VIRTUAL_HOST=expressjs-proxy.local.me # need to added into /etc/hosts on localhost
            - VIRTUAL_PORT=3000
          networks:
              - "nginx-proxy-net"

volumes:
    node_modules:

networks:
    nginx-proxy-net:
        external: true